[package]
name = "aelita_xrn"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
aelita_commons = { path = "../commons" }
xana-commons-rs = { workspace = true }
#
serde = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
