[workspace]
members = ["commons", "stor_diesel", "www", "xrn"]
resolver = "2"

default-members = ["xrn"]

[profile.release]
lto = "fat"

#
# Global Dependencies
#
[workspace.dependencies]
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
chrono = { version = "0.4.39", features = ["serde"] }
