[package]
name = "aelita_stor_diesel"
version = "0.1.0"
edition = "2024"

[dependencies]
aelita_xrn = { path = "../xrn" }
#
serde = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
#
diesel = { version = "2.2.0", features = ["mysql", "chrono"] }
dotenvy = "0.15"

