[package]
name = "aelita_stor_diesel"
version = "0.1.0"
edition = "2024"

[dependencies]
aelita_xrn = { path = "../xrn" }
#
thiserror = { workspace = true }
chrono = { version = "0.4.39", features = ["serde"] }
diesel = { version = "2.2.0", features = ["mysql", "chrono"] }
dotenvy = "0.15"
serde = { workspace = true }
